### ISSUE TITLE
Starting Location

### ISSUE THREAD

**Issue by Lloyd-Ann** [White-Edward/theHunt#11]
The starting location is currently statically set to 1,1.   This works fine, but the clue bag is also currently randomly placed on the map.   We either need to give the clue bag to the user right from the start, or start the user on the same map location that the cluebag gets put on.  Or force the cluebag to be at location 1,1.

**Comment by White-Edward** [comment]
It seem like it might be easy and makes the most sense to change the clue bag to start out at 1.1

**Comment by Lloyd-Ann** [comment]
Resolved
