### ISSUE TITLE
How the game ends

### ISSUE THREAD

**Issue by Lloyd-Ann** [White-Edward/theHunt#5]
There's a menu option to show game progress, which is based on how many riddles have been answered.  We need to figure out how to decide that the game has ended, either because the player has won or lost.

**Comment by Lloyd-Ann** [comment]
Originally we had the idea that there is some final question that all the clues help you answer.  Do we just want to change it so that the game ends when all the questions are answered?

**Comment by White-Edward** [comment]
How about if we make it so that after they answer all four riddles correctly then they win? That doesn't take care of the other 21 squares that are on the board, but it seems an easy way to finalize a win.

**Comment by Lloyd-Ann** [comment]
Are the 4 riddles you're talking about the complex equation ones?  Because all questions on the map are riddles, right?...

**Comment by ryanf03** [comment]
What if one square contains a vault or something and the clues give you the
combination.  At the final square you input the correct combination or
password and that will trigger the win. We can set it as a static combo.
It won't help replayability but should be simple to do.  That way when they
get a riddle correct, they receive a digit of the combo.

**Comment by Lloyd-Ann** [comment]
That could work.  We'd just have to put together a scene for the vault.  Or it could be a combo to escape the room you're trapped in or something.  Shouldn't be too hard.  We'd have to number the clues so the player knows what order to put them in.  I think there would be a clue for every question answered, not just for the complex equation questions, which means up to a 25 digit combo, but we could do it either way.  The vault could just be a game menu option rather than being placed on a map location.

We could also write a hint for the answer to each question in the question pool, and when a question is answered, you get a random hint to maybe help you answer a different question.  Or the hint could also just be the answer to another random question on the map...  I guess that doesn't help the end of the game though.

**Comment by Lloyd-Ann** [comment]
Do you want to take this one on Ryan?  Click the "assign yourself" link at the right under Assignee if so.
